added driver-service
DmitryPasmurtsev/cab-aggregator pull request #2
Opened 2023-12-11 23:36 UTC by DmitryPasmurtsev

2023-12-13 10:57 UTC, KirillKostylev requested changes

2023-12-13 10:57 UTC, KirillKostylev commented on driver-service/pom.xml
> +            <version>3.1.5</version>
Версии лучше вынести в пропертис

2023-12-13 10:57 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/controller/DriverController.java
> +    @ResponseStatus(value = HttpStatus.OK)
+ Хорошей практикой будет использовать 201 http статус для создания, а не просто 200
+ Ок ставится по дефолту, если метод отработал - не обязательно везде явно указывать 200

2023-12-13 10:57 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/dto/response/DriversListResponse.java
> +        this.drivers = passengers;
drivers = passengers ???

Можешь заменить множество конструкторов на билдер

2023-12-13 10:57 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/entity/Driver.java
> +@Data
На Ентити может быть опасно использовать @Data (особенно при наличии связей).
Лучше указать именно те аннотации, которые тебе нужны

2023-12-13 10:57 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/exceptions/handler/DriverExceptionHandler.java
> +        });
Если уже используешь стримы, попробуй сразу собрать лист мап

2023-12-13 10:57 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/exceptions/handler/DriverExceptionHandler.java
> +        error.put(SECOND_KEY, secondValue);
Можешь использовать Map.of()

2023-12-13 10:57 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/service/DriverService.java
> +@Component
А для чего тут это аннотация?

2023-12-13 10:57 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/service/impl/DriverServiceImpl.java
> +        else throw new NotFoundException("id", "Driver with id={" + id + "} not found");
у Optional есть удобный метод orElseThrow(). Он сделает код лучше

2023-12-13 10:57 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/service/impl/DriverServiceImpl.java
> +        return toDTO(driverRepository.findPassengerByPhone(phone));
Что будет если пользователь таким номером не найден? Пусть findPassengerByPhone возвращает Optional

2023-12-13 10:57 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/service/impl/DriverServiceImpl.java
> +    }
+ orElseThrow()
+ название метода не подразумевает return driver. У тебя есть метод findById с аналогичной логикой, подумай как можно избежать дубликацию кода

2023-12-13 10:57 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/service/impl/DriverServiceImpl.java
> +        List<DriverResponse> responseList = driverRepository.findAllByIsAvailableIsTrue(Sort.by(field)).stream().map(this::toDTO).toList();
Такое форматирование кода не очень читабельное, обычно при работе со стримами выносят каждый вызов метода на новую строку

2023-12-15 08:27 UTC, KirillKostylev requested changes

2023-12-15 08:27 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/service/impl/DriverServiceImpl.java
> +        if (driver == null) return null;
return null не лучший варик, старайся заменить на return Optional.
Но в данном методе, тебе лучше работать только с не null переменными (к примеру через @NotNull)

2023-12-15 08:27 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/service/impl/DriverServiceImpl.java
> +        if (!driverRepository.existsById(id))
Смотри, ты каждый раз когда тебе нужен Driver ты достаешь его из бд и конвертишь в дто (как в этом примере) + каждый раз делаешь проверку на null (твой toDto() может вернуть null) - получается бойлерплейт код. 
Как варик сделай приватный метод в сервисе, который будет возвращать сущность (в случее null прокидывать ошибку). И будешь его переиспользовать для всех нужд. 
Если есть вопросы, пингани меня в тимсе

2023-12-15 10:21 UTC, DmitryPasmurtsev commented on driver-service/src/main/java/com/modsen/driverservice/service/impl/DriverServiceImpl.java
> +        if (!driverRepository.existsById(id))
Метод checkExistence() я решил оставить, потому что в некоторых случаях нам не надо получать всю сущность из БД, а надо просто проверить есть она там или нет

2023-12-18 08:53 UTC, KirillKostylev requested changes

2023-12-18 08:53 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/exceptions/handler/DriverExceptionHandler.java
> +        ex.getFieldErrors().forEach(err -> responseList.add(Map.of(FIRST_KEY, err.getField(), SECOND_KEY, err.getDefaultMessage())));
Сделай через Map

2023-12-18 08:53 UTC, KirillKostylev commented on driver-service/src/main/java/com/modsen/driverservice/service/impl/DriverServiceImpl.java
> +        } catch (NotFoundException ex) {
Заиспользовать Optional

2023-12-19 09:01 UTC, KirillKostylev approved these changes

2023-12-19 17:07 UTC, merged