feature/ride service
DmitryPasmurtsev/cab-aggregator pull request #3
Opened 2023-12-19 21:30 UTC by DmitryPasmurtsev

2023-12-20 09:25 UTC, AbandonedScope requested changes

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/controller/PromoCodeController.java
> +        else return promoCodeService.getList();
Во первых - логика в контроллерах быть не должна, во вторых - даже если if из одной строки, всё равно ставь фигурные скобки, так читаемее
Просто передавай параметры в сервис, а он уже сам будет их проверять

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/controller/PromoCodeController.java
> +    @PatchMapping("/{name}")
А чего patch?

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/controller/RideController.java
> +        else return rideService.getAllRidesForPassenger(id);
То же самое

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/controller/RideController.java
> +        return new StringResponse("Ride with id={" + id + "} has been successfully rejected");
Пусть сервис и формирует этот ответ

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/dto/request/DriverFinishRequest.java
> +    @NotNull(message = "Driver's id should not be empty")
Обычно, сообщения, которые отправляются на фронт локализуются
Смотри, есть два варианта: либо ты сам их читаешь из файла(и соответственно создаёшь несколько файлов для разных локалей), либо ты отправляешь только ключ сообщения(например, driver.id.notEmpty), и фронт сам разбирается, какое сообщение ему по этому ключу отобразить
Смотри сам, какое решение тебе ближе, я приму и то и другое

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/exceptions/handler/RideExceptionHandler.java
> +        return new ResponseEntity<>(createResponse(ex.getPropertyName(), ex.getMessage()), HttpStatus.BAD_REQUEST);
```suggestion
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(createResponse(ex.getPropertyName(), ex.getMessage()));
```

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RatingServiceImpl.java
> +        if(ratings.isEmpty()) return new RatingResponse(id, null);
Во первых - фигурные скобки и новая строка, во вторых, можно и без этого, просто пустой список вернётся

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        ride.setStatus(Status.ACCEPTED);
Вынеси в отдельный метод

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        } else ride.setFinalCost(ride.getInitialCost());
В фигурные скобки, с новой строки

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +            ride.setFinalCost(Math.round(ride.getInitialCost() * coefficient * 100.0) / 100.0);
Вынеси это (Math.round(ride.getInitialCost() * coefficient * 100.0) / 100.0) во что-то по типу calculateCost

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +    }
В этом случае, нужно было написать интерфейс, который бы имел необходимые методы, создать его реализацию(по сути заглушку) и всё, тогда не пришлось бы в следующем ПР-е менять этот метод, просто другую реализацию в контейнер бы запихнул, и всё бы работало

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +            throw new WrongStatusException("status", "Ride with id={" + id + "} not started");
...

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        if (dto.getRatingToDriver() != null) ride.getRating().setDriverRating(dto.getRatingToDriver());
Скобки, новая строка

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +            throw new WrongStatusException("status", "Ride with id={" + id + "} has wrong status");
Скобки

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        rideRepository.save(ride);
Разделяй пустыми строками логические блоки, так код становится понятнее
```suggestion
        Ride ride = getEntityById(id);
        
        checkPassengerAccess(ride, dto.getUserId());
        checkPossibilityToReject(ride);
        
        ride.setStatus(Status.REJECTED);
        rideRepository.save(ride);
```

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +            throw new WrongStatusException("status", "Ride with id={" + ride.getId() + "} can`t be rejected");
Скобки

2023-12-20 09:25 UTC, AbandonedScope commented on ride-service/src/main/resources/db/changelog/db.changelog-master.xml
Посмотри [вот это видео](https://www.youtube.com/watch?v=JTdcd4DYgEI&t=2014s&ab_channel=TheUsharik), там рассказывается о том, как правильно организовать миграции, и поправь свои

2023-12-21 14:08 UTC, AbandonedScope requested changes

2023-12-21 14:08 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/controller/PromoCodeController.java
> +    public PromoCodeDTO createPromo(@RequestBody @Valid PromoCodeDTO dto) {
DTO -> Dto

2023-12-21 14:08 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/exceptions/handler/RideExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(createResponse(ex.getField(), ex.getMessage()));
Вызов body с новой строки должен быть, более читаемо тогда

2023-12-26 19:41 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/exceptions/handler/RideExceptionHandler.java
> +    static final String SECOND_KEY = "message";
Переименуй, чтобы было понятно, что за константы

2023-12-26 19:41 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/PromoCodeServiceImpl.java
> +        if(promoCodeRepository.existsById(dto.getName())){
```suggestion
        if (promoCodeRepository.existsById(dto.getName())){
```

2023-12-26 19:42 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/PromoCodeServiceImpl.java
> +        }
```suggestion
        if (promoCode.isPresent()) {
            return promoCode.get();
        }
```

2023-12-26 19:43 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/PromoCodeServiceImpl.java
> +        }
```suggestion
        if (offset != null && page != null && field != null) {
            return getAllWithPaginationAndSorting(offset, page, field);
        } else if (offset != null && page != null) {
            return getAllWithPagination(offset, page);
        } else if (field != null) {
            return getAllWithSorting(field);
        }
        
        return getAll();
```

2023-12-29 07:45 UTC, AbandonedScope approved these changes

2023-12-29 07:45 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/PromoCodeServiceImpl.java
> +        throw new NotFoundException("name", "message.promo-code.notFound");
```suggestion
        return promoCodeRepository.findById(name)
        .orElseThrow(() -> new  NotFoundException("name", "message.promo-code.notFound"));
```

2023-12-29 07:45 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        if (!promoCodeName.isEmpty()) {
А если null?

2024-01-05 14:17 UTC, DmitryPasmurtsev commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        if (!promoCodeName.isEmpty()) {
Заменил isEmpty на isBlank. Это проверка на пустую строку и null

2024-01-05 15:50 UTC, merged