drivers, passengers, payments communication
DmitryPasmurtsev/cab-aggregator pull request #6
Opened 2024-01-06 12:38 UTC by DmitryPasmurtsev

2024-01-09 10:31 UTC, IvanKiselevichWork requested changes

2024-01-09 10:31 UTC, IvanKiselevichWork commented on driver-service/src/main/java/com/modsen/driverservice/controller/DriverController.java
>      @DeleteMapping("/{id}")
Почему на блокировку delete метод, а не например post? И урл тоже нужно понятнее сделать, типа {id}/block

2024-01-09 10:31 UTC, IvanKiselevichWork commented on driver-service/src/main/java/com/modsen/driverservice/controller/DriverController.java
> +    public void changeAvailability(@PathVariable Long id) {
Метод, который делает что-то в зависимости от какого-то внутреннего статуса - не ок, нужно делать явные методы, и передавать id и нужный статус

2024-01-09 10:31 UTC, IvanKiselevichWork commented on driver-service/src/main/java/com/modsen/driverservice/kafka/NewRideConsumer.java
> +    void rideCreationListener() {
Зачем listener, который не принимает сообщение?

2024-01-09 10:31 UTC, IvanKiselevichWork commented on passenger-service/src/main/java/com/modsen/passengerservice/controller/PassengerController.java
>      public void deletePassenger(@PathVariable Long id) {
То же самое

2024-01-09 10:31 UTC, IvanKiselevichWork commented on payment-service/src/main/java/com/modsen/paymentservice/controller/PaymentController.java
> +    public void checkBalance(@RequestBody CustomerChargeRequest dto) throws StripeException {
В чем смысл этого и следующего методов, если они ничего не возвращают? Нужно возвращать что-то, а не использовать эксепшены не по делу

2024-01-11 17:18 UTC, DmitryPasmurtsev commented on driver-service/src/main/java/com/modsen/driverservice/kafka/NewRideConsumer.java
> +    void rideCreationListener() {
Этот listener принимает сообщение о том, что в сервисе поездок была создана новая поездка. Поиск свободного водителя не использует информацию из этого сообщения. Думаю, что в будущем сообщение можно будет использовать для сохранения лога (у нас есть такой спринт), а пока оно не используется

2024-01-12 14:31 UTC, IvanKiselevichWork approved these changes

2024-01-15 11:37 UTC, merged